name: magento-l18n-extractor
description: "Extracts l18n from magento module"

branding:
  icon: globe
  color: green

inputs:
  module_path:
    default: .
    description: "Location of magento module"
    required: false

  output_file_path:
    description: "Location of generated translations"
    required: true

runs:
  using: docker
  image: Dockerfile
